--- # Create ec2 instance playbook
- name: Provision temporary dev server
  hosts: localhost
  connection: local
  tags: provision
  gather_facts: false
  vars:
      keypair: ""
      disk_vols: "15"
      instance_type: "t2.medium"
      instance_ids: "i-45e2Ax"
      image: "ami-2c6e7e42"
      group: "default"
      region: "ap-northeast-1"
      inst_name: "dev03.moneylion.com"
      serv_env: "Development"
      serv_class: "General"
      provisionby: "Ansible"

  tasks:
    - name: Create Instance (Debian 8 HVM)
      ec2: image={{ image }}
           instance_ids= {{ instance_ids }}
           instance_type={{ instance_type }}
           keypair={{ keypair }}
           instance_tags='{"Name":"{{ inst_name }}","Environment":"{{ serv_env }}","Class":"{{ serv_class}}","Provision":"{{ provisionby }}"}'
           region={{ region }}
           group={{ group }}
           assign_public_ip=yes
           wait=true
      register: ec2_info

    - name: Set Instance volume size
      ec2_vol: 
           instance= {{ item.id }}
           volume_size={{ disk_vols }}

    - name: Add new instances to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
