--- # Create ec2 instance playbook
- name: Provision temporary dev server
  hosts: localhost
  connection: local
  tags: provision
  gather_facts: false
  vars:
      keypair: ""
      disk_vols: "10"
      instance_type: "t2.medium"
      image: "ami-55be6b36"
      group: "default"
      region: "ap-southeast-1"
      inst_name: "dev03.moneylion.com"
      serv_env: "Development"
      serv_class: "General"
      provisionby: "Ansible"

  tasks:
    - name: Create Instance (Debian 8 HVM)
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           keypair={{ keypair }}
           instance_tags='{"Name":"{{ inst_name }}","Environment":"{{ serv_env }}","Class":"{{ serv_class}}","Provision":"{{ provisionby }}"}'
           region={{ region }}
           group={{ group }}
           volumes={{ disk_vols }}
           assign_public_ip: yes
           wait=true
      register: ec2_info

    - name: Add instances to host group
      add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item[ec2launch.check.ip] }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: Associate Elastic IP to instances
      ec2_eip:
       region={{ region }}
       in_vpc=yes
       instance_id= {{ launched.instances[item.0].id }} 
       ip= {{ item.1 }}
      with_indexed_items: "{{ ec2launch.elastic_ips }}"
      when: ec2launch.elastic_ips
  
    - name: Add launched instances to host group
      add_host:
      hostname: "{{ item.id }}.{{ ec2launch.inventory_group }}"
      groupname: "{{ ec2launch.inventory_group }}"
      ansible_ssh_host: "{{ item[ec2launch.check.ip] }}"
      ansible_user: "{{ ec2launch.ansible_user }}"
      ansible_ssh_private_key_file: "{{ ec2launch.ansible_key }}"
 :   with_items: launched.instances

