--- # Create ec2 instance playbook
- name: Provision temporary dev server
  hosts: localhost
  connection: local
  tags: provision
  gather_facts: false
  vars:
      keypair: ""
      instance_type: "t2.medium"
      image: "ami-55be6b36"
      group: "default"
      region: "ap-southeast-1"
      inst_name: "dev03.moneylion.com"
      serv_env: "Development"
      serv_class: "General"
      provisionby: "Ansible"

  tasks:
    - name: Create Instance (Debian 8 HVM)
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           keypair={{ keypair }}
           instance_tags='{"Name":"{{ inst_name }}","Environment":"{{ serv_env }}","Class":"{{ serv_class}}","Provision":"{{ provisionby }}"}'
           region={{ region }}
           group={{ group }}
           wait=true
      register: ec2_info

    - name: Add instances to host group
      add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

   -name: set EC2 hostname 
    hosts: ec2hosts
    gather_facts: true
    tasks:
    -name: Change with proper hostname according EC2 Tag Name
     command: echo {{ inst_name }} > /etc/hostname
